TransactionType.create(description: 'Débito',                 origin: 0)
TransactionType.create(description: 'Boleto',                 origin: 1)
TransactionType.create(description: 'Financiamento',          origin: 1)
TransactionType.create(description: 'Crédito',                origin: 0)
TransactionType.create(description: 'Recebimento Empréstimo', origin: 0)
TransactionType.create(description: 'Vendas',                 origin: 0)
TransactionType.create(description: 'Recebimento TED',        origin: 0)
TransactionType.create(description: 'Recebimento DOC',        origin: 0)
TransactionType.create(description: 'Aluguel',                origin: 1)